### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by FeryET** [omni-us/jsonargparse#104]
There is this conda pacakge: https://anaconda.org/conda-forge/jsonargparse, but it is not documented in this repo + there is no description about whether this conda package comes with optional tags like `signatures`, etc. 

Could you elaborate more on this?

**Comment by mauvilsa** [comment]
I am not very familiar with conda and I had no idea that there was a conda package for jsonargparse. That package was created independently of this repo which is why there is no mention of it.

After a bit of investigation I have found out that an automatic conda package creation was configured and is maintained by @olegtarasov (see [staged-recipes/pull/16043](https://github.com/conda-forge/staged-recipes/pull/16043) and [conda-forge/jsonargparse-feedstock](https://github.com/conda-forge/jsonargparse-feedstock)).

If I download one of the conda package files in https://anaconda.org/conda-forge/jsonargparse/files I only see the jsonargparse files, not any dependencies. I don't know how conda packages work but I guess it wouldn't be that all dependencies are included in the package. But no idea if by installing that package other dependency packages are installed along with it.

From what I read, conda does not support the native python extras requires (optional tags) and the alternative is manually creating metapackages for every extras require. I also read that a conda-forge package requires all of its dependencies to also be in conda-forge. For the specific case of `signatures` the only additional dependency is [docstring_parser](https://github.com/rr-/docstring_parser) which is not in conda-forge thus I guess it would need to be added. Since I don't use conda and are not very familiar with it, I will not attempt to add new conda packages or create metapackages. But it would be great if conda users take care of this.
