### ISSUE TITLE
Parsing of List[str] fails using command line

### ISSUE THREAD

**Issue by stecklin** [omni-us/jsonargparse#112]
Consider the following example:

_my_script.py_
```python
from typing import List

from jsonargparse import CLI


def my_list_function(str_list: List[str]):
    print(str_list)


if __name__ == '__main__':
    CLI()
```

Running `python my_script.py ["abc"]` works, while running `python my_script.py ["123"]` fails.

> error: Configuration check failed :: Parser key "str_list": Expected a <class 'str'> but got "123"

Some related things I tried:
* parsing with a config file works as long as you use quotes ("123")
* simple string arguments are parsed correctly, only happens for lists of strings

**Comment by mauvilsa** [comment]
What is happening here is not due to python but the shell. The value of the argument that reaches python is an unquoted integer which is why there is the error saying that did not get an str. This can be observed for example if you do in bash

```bash
$ echo python my_script.py ["123"]
python my_script.py [123]
```

To make this work you need to either quote the entire argument or escape the double quotes, e.g.

```bash
$ python my_script.py '["123"]'
['123']
```
