### ISSUE TITLE
inherit ActionConfigFile from _AppendAction for better compatible with shtab

### ISSUE THREAD

**Issue by tshu-w** [omni-us/jsonargparse#127]
I open a new issue to discuss it and close the original one https://github.com/omni-us/jsonargparse/issues/108.

shtab use option type to decide completion nargs format in this [line](https://github.com/iterative/shtab/blob/7f25585e4b7a5552daeb1cc03d857108332f1a86/shtab/__init__.py#L467), however ActionConfigFile doesn't inherit from any of `OPTION_MULTI = _AppendAction, _AppendConstAction, _CountAction`, should `ActionConfigFile` inherit from `_AppendAction` as it accept `python cli.py --config config.yaml --confg config2.yaml`?

**Comment by mauvilsa** [comment]
`ActionConfigFile` inheriting from `_AppendAction` would only make sense if somehow it could use part of that class's functionality, e.g. doing `super().__init__(...)` or `super().__call__(...)`. But there is nothing that can be reused from that class. Adding it just so that shtab handles it in some particular way would be a hack and not a good programing practice. Therefore, I will not do this.

@tshu-w you have suggested doing this but gave no motivation for it. What does it do?

Something that wouldn't be a hack and potential addition in jsonargparse could be:

```python
import shtab
from jsonargparse import ActionConfigFile
shtab.OPTION_MULTI = shtab.OPTION_MULTI + (ActionConfigFile,)
```

Though, I don't know if `OPTION_MULTI` can be considered stable and part of the public API of shtab. Would be better to have an explicit public function to register such things. @casperdcl a comment from you could be useful.

**Comment by tshu-w** [comment]
> Adding it just so that shtab handles it in some particular way would be a hack and not a good programing practice. Therefore, I will not do this.

Thanks for you reply. I see.

> @tshu-w you have suggested doing this but gave no motivation for it. What does it do?

I don't particularly understand what you mean. If I understand correctly, the reason I did this was so that shtab would generate the correct zsh completion function for LightningCLI, since --config takes multiple arguments, but now zsh no longer completes --config after entering it once.

Anyway I understand your idea, and also implemented it like the following way.

> ```python
> import shtab
> from jsonargparse import ActionConfigFile
> shtab.OPTION_MULTI = shtab.OPTION_MULTI + (ActionConfigFile,)
> ```

I don't think this is something jsonargparse needs to handle anymore, so I closed the issue and will talk to @casperdcl about `OPTION_MULTI` if I needed.
