### ISSUE TITLE
How can I add a param as List or Dict of some speific classes?

### ISSUE THREAD

**Issue by shenmishajing** [omni-us/jsonargparse#131]
The CLI of pytorch lightning only support one optimizer and one lr_scheduler, as [here](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html#optimizers-and-learning-rate-schedulers).

I want to rewrite the code for registering configure_optimizers method, so I want change the param optimizer and lr_scheduler from just one optimizer or lr_scheduler to a List of optimizer and a List of lr_scheduler_config as [here](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html#configure-optimizers).

But, I do not find some doc about the List of some classes. So, how can I do this? Or just, we can not do this by jsonargparse?

**Comment by mauvilsa** [comment]
In jsonargparse adding an argument which is a list or dict of classes is done by defining the type. For example:

```python
parser.add_argument("--list1", type=List[BaseClass])
parser.add_argument("--list2", type=List[Union[BaseClassA, BaseClassB]])
parser.add_argument("--dict", type=Dict[str, BaseClass])
```

However, it is not as simple for pytorch optimizers and schedulers. The problem is that an optimizer requires as input the parameters of the model. Thus the first init arg must be skipped and the instantiation can't be done by jsonargparse. In the case of schedulers, an optimizer is required, making it a similar case.

Because of these particularities you should create an issue in the pytorch-lightning repo instead of here. There it can be discussed how to do this with LightningCLI.

**Comment by shenmishajing** [comment]
Thanks for your reply, I will close this issue and create an issue in pytorch-lightning repo.
