### ISSUE TITLE
Required arguments? 

### ISSUE THREAD

**Issue by Solvik** [omni-us/jsonargparse#2]
Kudos for the project, it solves a lot of problem for me :)

I've tried to get my head around required arguments, but it seems that argparse takes over jsonargparse in the order.
Even though the variable is present in the file, it throws the error.

```python
import jsonargparse

p = jsonargparse.ArgumentParser(
    default_config_files=[
        '~/config.yaml'
    ],
    prog='test',
)

p.add_argument('-c', '--config', action=jsonargparse.ActionConfigFile)
p.add_argument('-a', required=True)
p.add_argument('-b', required=False)
print(p.parse_args())
```

```
$ cat config.yaml
a: value1
b: value2
```

It gives:
``` 
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    print(p.parse_args())
  File "/usr/local/lib/python3.7/site-packages/jsonargparse.py", line 199, in parse_args
    cfg = super().parse_args(args=args, namespace=namespace)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1749, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 2016, in _parse_known_args
    ', '.join(required_actions))
  File "/usr/local/lib/python3.7/site-packages/jsonargparse.py", line 478, in error
    raise ParserError(message)
jsonargparse.ParserError: the following arguments are required: -a
```

Also, it seems that `default_config_files` doesn't work:
``` 
$ python3 test.py
namespace(a=None, b=None, config=None)
```

**Comment by mauvilsa** [comment]
@Solvik thank you for reporting your findings.

I have just fixed the problem about `default_config_files` not working.

Regarding the main issue, it does consider a possible expected behavior that I had not thought about. This is, if an argument is required and its value is given through a config file, be it through default_config_files or ActionConfigFile, then parse_args should not complain about the missing argument. Unfortunately, this is not a trivial fix. This package just extends argparse and the values from the config file are being given to argparse's parse_args through the namespace argument (https://docs.python.org/3.6/library/argparse.html#the-namespace-object). So turns out that argparse does not consider the values in the given namespace when considering the required arguments.

I will think about this to see if there is some easy way to implement this behavior. For now, the current behavior is, if an argument is required, then it must be provided through a command line argument.

**Comment by Solvik** [comment]
Thanks for the fix

Regarding the required argument feature, one approach could be to implement a library based logic instead of using argparse one.
Like `my_required=jsonargparse.ANY` to say it's required from cli/env/config or `my_required=jsonargparse.CONFIG | jsonargparse.ENV` to say it's required from config or env only.

What do you think?

**Comment by mauvilsa** [comment]
The problem is not deciding how to allow the user to specify from which source the argument is required. The problem is that argparse is the one parsing the arguments, and there is not way to tell it to not fail if a required argument is not given. And this would be necessary to later check if it has been given from another source.

**Comment by mauvilsa** [comment]
@Solvik I implemented a way so that argparse does not do the required check, but then the check is done considering all possible sources. This should be solved, but please check.

**Comment by Solvik** [comment]
Awesome ! I'm gonna perform some testing, thanks a lot !
