### ISSUE TITLE
Link arguments "Target key must be for an individual argument"

### ISSUE THREAD

**Issue by samvanstroud** [omni-us/jsonargparse#208]
## 🐛 Bug report

Certain argument links produce an error. For example, using a subclass of the `LightningCLI` that links the trainer `default_root_dir` to the logger `save_dir` arguments, the following error occurs.

```bash
Traceback (most recent call last):
...
  File ".../clitest.py", line 8, in add_arguments_to_parser
    parser.link_arguments("trainer.default_root_dir", "trainer.logger.init_args.save_dir")
  File ".../lib/python3.10/site-packages/jsonargparse/link_arguments.py", line 379, in link_arguments
    ActionLink(self, source, target, compute_fn, apply_on)
  File ".../lib/python3.10/site-packages/jsonargparse/link_arguments.py", line 141, in __init__
    raise ValueError(f'Target key "{target}" must be for an individual argument.')
ValueError: Target key "trainer.logger.init_args.save_dir" must be for an individual argument.
```

A link in the the other direction `save_dir` -> `default_root_dir` seems to work okay,
I suspect the issue may be to do with the fact that the target key exists within an optional `trainer.logger` class.

### To reproduce

```python
from pytorch_lightning.cli import LightningCLI
from pytorch_lightning.demos.boring_classes import BoringDataModule, DemoModel


class MyCLI(LightningCLI):
    def add_arguments_to_parser(self, parser) -> None:
        #parser.link_arguments("trainer.logger.init_args.save_dir", "trainer.default_root_dir") # works 
        parser.link_arguments("trainer.default_root_dir", "trainer.logger.init_args.save_dir") # error


def cli_main():
    cli = MyCLI(DemoModel, BoringDataModule)


if __name__ == "__main__":
    cli_main()
```

### Expected behavior

I'm opening an issue here as:
- It would be nice to allow the link to be ignored when the target is null (perhaps with an additional parameter to the `link_arguments` function e.g. `ignore_null_target`)
- In any case, the error message could be improved.

### Environment

- jsonargparse 4.18.0
- Python 3.10.6

**Comment by mauvilsa** [comment]
Thank you very much for reporting!

I tried the reproduction script with jsonargparse 4.18.0 and python 3.10 and the error message is not the one described. The actual error message is `ValueError: No action for key "trainer.default_root_dir"`. Note that the reproduction script defines two links that create a loop, i.e., `a -> b` and `b -> a`. This should be an error and not an ignore. Also note that for links applied on parse there is no reason to support links in a chain, e.g., `a -> b` and `b -> c`, since this can be done as `a -> b` and `a -> c`.

> - It would be nice to allow the link to be ignored when the target is null (perhaps with an additional parameter to the link_arguments function e.g. ignore_null_target)

Ignore is already the behavior when the target is a parameter in a subclass, which at the moment of creating the link it is not known if the class does have this parameter. The link can be created without problem, and at run time if the class does not have this parameter the link is ignored. Using the target of a previous link as source of an another link is a different case and can be detected as invalid on link creation.

> - In any case, the error message could be improved.

In pull request #218 implements a more specific error message for this case.

**Comment by samvanstroud** [comment]
Thanks a lot for the response and the PR.

Sorry, the example could have been more clear -- I meant for only one of the `link_arguments` calls to be ran at a time. The first runs (on its own) without problems, while the second errors with the error I reported initially when run on its own. I wasn't trying to create a circular link but rather I would have expected the links to be commutative in the sense that if `a -> b` works o then `b -> a` should also work (if both are not defined).

**Comment by mauvilsa** [comment]
> I meant for only one of the `link_arguments` calls to be ran at a time. The first runs (on its own) without problems, while the second errors with the error I reported initially when run on its own.

Oh, right. I could have understood that. I guess I have too many things in my head at the moment. Will look at the issue later.
