### ISSUE TITLE
Confusing None vs null in the help message

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#23]
Arguments whose default is `None` appear in the help message as `(default: None)` even though they have to be passed as `--value=null`. This can be confusing for users.

I can think of a few options:
- Show `(default: null)` in the help message instead
- Add support for `value=None` (null|none). Just as booleans do with (true|yes|false|no)
- Just support `value=None`. Why was `null` chosen if it's not in the python language? is it a limitation of json/yaml?

What do you think?

**Comment by mauvilsa** [comment]
> Arguments whose default is `None` appear in the help message as `(default: None)` even though they have to be passed as `--value=null`. This can be confusing for users.

I completely agree and was aware of it.

> Why was `null` chosen if it's not in the python language? is it a limitation of json/yaml?

What I did to be able to support unbounded nested depth of complex type hints was to convert them into a jsonschema. So yes, it is a limitation of json/jsonschema since there it is `null` instead of `None`. Supporting only `None` would break the json support. Supporting both `None` and `null` would be ugly and possibly problematic since it could be possible that someone wants input None as a string. Probably your first option is what makes most sense. Though still not sure.
> 
> 
> What do you think?

**Comment by carmocca** [comment]
> Supporting both None and null would be ugly and possibly problematic since it could be possible that someone wants input None as a string. Probably your first option is what makes most sense. Though still not sure.

I am fine with option 1.

In general, I believe the defaults shown in the help message should be represented the way they have to be passed as a parameter. Another example of this disparity are lists which appear as `(default: [1, 1, 1])` but are passed as `--value=[1,1,1]`.

**Comment by mauvilsa** [comment]
The lists can be passed with spaces. Just that you need to quote it, otherwise the shell will treat it as multiple arguments.

Another discrepancy that probably I should change is related to booleans. As you said currently they can be given as true|yes|false|no. But if it is a bool inside a complex type hint, e.g. `Dict[str, Union[bool, str]]` then it can only be true|false. This is because the bool I implemented it long ago in some other way. To be consistent it wold be best if bools are treated the same way always.

**Comment by mauvilsa** [comment]
Actually, nested booleans also accept yes|no. I did not think that pyyaml would parse `yaml.safe_load('{"k": yes}')` and `yaml.safe_load('{"k": no}')` as `{'k': True}` and `{'k': False}`, but it does.

**Comment by carmocca** [comment]
Looking at its docs, on|off also works

**Comment by mauvilsa** [comment]
Default None is now displayed as null in the help.
