### ISSUE TITLE
Support None args through the utilisation of Optional type hints

### ISSUE THREAD

**Issue by nicoloesch** [omni-us/jsonargparse#265]
## 🚀 Feature request

With the introduction of the [`typing.Optional`](https://docs.python.org/3/library/typing.html#typing.Optional) typing hint, the support for `None` command line args could be a useful feature. In my specific case, I would love to turn off specific modules by specifying the associated argument with `None` (e.g. activation functions, normalisation etc.). However, specifying `None` as a command line argument is currently not supported and results in a error message.

### Motivation

Initialising class attributes with `None` by specifying `Optional[T]` would allow more flexibility. Particularly in combination with `typing.Literal`, arguments can be exactly limited to both real ones and `None` (`Optional[Literal['ReLU']]`), e.g. `--activation=ReLU` results in a ReLU activation function, whereas `--activation=None` would result in the non-existence of the said activation function (based on the code within the class that adds the activation function only if the argument is not None).

### Pitch

Ability to specify command line arguments to be of type `None` with correct parsing and no error message. Simpile example would be 

```python
class TestClass:
    def __init__(self,
                 foo: Optional[int]):  # Either None or an int but not default to None as specification is required in my case.
        self._foo = foo


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_class_arguments(TestClass, 'test_class.init')

    cfg = parser.parse_args(['--test_class.init.foo=None'])

    test_class = TestClass(**namespace_to_dict(cfg.test_class.init))
```

Currently, this example leads to the following error message:
```
usage: test_app.py [-h] [--test_class.init CONFIG] --test_class.init.foo FOO
test_app.py: error: Parser key "test_class.init.foo":
  Does not validate against any of the Union subtypes
  Subtypes: (<class 'int'>, <class 'NoneType'>)
  Errors:
    - Expected a <class 'int'>
    - Expected a <class 'NoneType'>
  Given value type: <class 'str'>
  Given value: None
```

### Alternatives
Obviously, one could also specify a condition within the class that sets the attribute to `None` depending on a specific argument value e.g. `foo=-1`, or only adds the respective functionality if instead of the `None` condition, a different one is met. However, `None` would be a safer option imo.

**Comment by mauvilsa** [comment]
`Optional` is already supported, see in the docs [type-hints](https://jsonargparse.readthedocs.io/en/stable/#type-hints). What jsonargparse uses to load is pyyaml, so the format that it expects is yaml/json. Thus you must give `null` instead of `None`. This can also be seen when you use the `--help` or `--print_config` options.

The error message could

**Comment by mauvilsa** [comment]
A minor unrelated note. To instantiate classes, better to do as

```python
init = parser.instantiate_classes(cfg)
```

Instantiating manually like above does work, even without converting to a dict. But when using more advanced features, like argument linking, then it will not work as expected.

**Comment by nicoloesch** [comment]
Thanks for this really quick response! I have seen the support within the docs but maybe I am expecting a different behaviour.
I just tried by specifying `null` (is this what you meant or should I rather load it through a `.yaml` config?)

```python
parser = ArgumentParser()
parser.add_class_arguments(TestClass, 'test_class.init')
cfg = parser.parse_args(['--test_class.init.foo', 'null'])
init = parser.instantiate_classes(cfg)
```

but I still get an error message:

```
test_app.py: error: Configuration check failed :: Key "test_class.init.foo" is required but not included in config object or its value is None.
```
I could set the typing hint of `foo` in above class as follows:

``` python
foo: Optional[int] = None
```
which results in a working project. However, I want the user to explicitly specify it and especially utilise it in combination with `typing.Literals`. The latter is somewhat impaired because if I specify a default value for any class argument, the typing checking does not really work anymore at least when I tried it. 

E.g. if I specify `Optional[Literal['a', 'b', 'c']] = None` and I pass e.g. `'d'`, the variable is set to None instead of giving the error message that only `'a', 'b', 'c', None` are allowed. 

Am I doing something wrong here?

Thank you again for your help! I really appreciate it!

**Comment by mauvilsa** [comment]
> I just tried by specifying `null` (is this what you meant or should I rather load it through a `.yaml` config?)

Yes, I meant specifying `null` from the command line. pyyaml is used to parse both from command line and config files.

> but I still get an error message:

Unfortunately this is how it works. By default in argparse, when an argument is unset, it gets the value `None`, conversely a value of `None` means the argument is unset. In a class signature, if a parameter does not have a default, it is considered to be required. Which is why it fails without a default and works when you set the default to `None`. jsonargparse could be modified so that some other value is used to distinguish unset and `None`. However, this is a big effort and will not happen any time soon.

> However, I want the user to explicitly specify it and especially utilise it in combination with `typing.Literals`. 

If anyway in your class you are going to handle input strings, just set the type hint as `Literal['a', 'b', 'c', 'None']` and no default to make it required.
