### ISSUE TITLE
Automatically add Optional type to kwargs with None default 

### ISSUE THREAD

**Issue by mpariente** [omni-us/jsonargparse#30]
I was having a look a [this PR](https://github.com/PyTorchLightning/pytorch-lightning/pull/4492) and decided to give it a try. 

```python
# In parsing_workout.py
class Dummy:
    def __init__(self, dummy: float = None):
        pass
```

Then execute
```bash
python parsing_workout.py --print_config > conf.yml
python parsing_workout.py --config conf.yml
```

I get the following error :
```traceback
parsing_workout.py: error: Parser key "data.dummy": float() argument must be a string or a number, not 'NoneType'
```

Notably, this doesn't crash with IPython. 

I think it would make sense to automatically add `Optional` to the type in those cases, WDYT?

**Comment by mauvilsa** [comment]
Automatically adding `Optional` would be an easy change. I agree it is nice that a `None` default is implicitly an optional, since adding the optional to the type seems kind of redundant. Though it seems that this implicit optional is discouraged and in the near future by default will not be a valid type hint, see https://github.com/python/mypy/issues/9091 and https://github.com/python/peps/pull/689. So I have a bit of mixed feelings about this.

**Comment by mpariente** [comment]
Wasn't aware about this. I understand. 
Maybe support an `--implicit-optional` flag as `mypy` is going to make?

**Comment by mauvilsa** [comment]
I think that maybe we just add the implicit optional in jsonargparse without any option. Anyway mypy will show people the error when this is no longer a valid type. The ithe implicit optional code in jsonargparse would not be used, but at least it doesn't hurt.

**Comment by mpariente** [comment]
Sounds good.

**Comment by mauvilsa** [comment]
This is now implemented. Please check.

**Comment by mauvilsa** [comment]
This is now in release v3.2.0.

**Comment by mpariente** [comment]
Thanks! I'll have a look soon
