### ISSUE TITLE
Parsing a Union of int and str from config.json casts type incorrectly

### ISSUE THREAD

**Issue by Sileadim** [omni-us/jsonargparse#35]
When the types in a Union are a str and and int, a str in the config.json is parsed as a int.

Example config:
```json
{ "int_or_str": "1" }
```
Example script:
```python
from jsonargparse import ArgumentParser, ActionConfigFile
from typing import Union

if __name__ == "__main__":

    union = Union[str,int]
    parser = ArgumentParser()
    parser.add_argument("--cfg", action=ActionConfigFile)
    parser.add_argument("--int_or_str", type=union )
    args = parser.parse_args()
    print(args.int_or_str, type(args.int_or_str))
```

Output:
```shell
python test.py --cfg config.json
typing.Union[str, int]
1 <class 'int'>
```

**Comment by mauvilsa** [comment]
The same code is used to parse values from any source, and in the case of command line arguments and environment variables, the values are always originally strings. Making this work would require a big change. Furthermore, I don't think it makes sense to implement this, since the idea is that the parsers should work consistently for any source, which it wouldn't be in this case.

Do you really need an argument that can be both any int and any string? If you need an argument that can be an int and a subset of strings, then make the argument more specific. To restrict which strings can be accepted you can use `restricted_string_type` or an `Enum`.

**Comment by Sileadim** [comment]
Pytorch lightning trainer has this as one of the options, see here: https://pytorch-lightning.readthedocs.io/en/latest/multi_gpu.html#select-gpu-devices

**Comment by mauvilsa** [comment]
> Pytorch lightning trainer has this as one of the options, see here: https://pytorch-lightning.readthedocs.io/en/latest/multi_gpu.html#select-gpu-devices

I guess you mean you want to select one specific gpu. If so `[1]` should give the same result as `'1'`.

**Comment by Sileadim** [comment]
Yeah in this case it's an option. But you should not answer my issues on our vacation ;)
