### ISSUE TITLE
Recursive configuration files.

### ISSUE THREAD

**Issue by ArenaGrenade** [omni-us/jsonargparse#415]
## 🚀 Feature request

Configuration files that link to other config files.

### Motivation

Imagine a scenario, when we need multiple base configurations, but then we want to mix and match each of these, in such a scenario, a recursive config would be helpful, as it would mean we do not repeat the same config multiple times. In fact, we can even use it for a single config, but multiple experiments. We can link a base configuration file and override only some arguments for different experiments. Both the above cases actively appear in machine learning tuning.

### Pitch

- Allow configuration files to contain references to other configuration files. (child config -> parent config linking)
- Map all the linked parent config parameters as the base set of parameters. Any additional parameters present in the child config must override any parent config specifications.
- The config files and linkages can be processed recursively and a temporary config file could be created during file load/parsing, which we can then parse normally.

### Alternatives

Create so many configurations for each experiment / for each combination of sub-module variations.

**Comment by mauvilsa** [comment]
I am not entirely sure what you mean here by "recursive". But there are already several ways to reuse configs for multiple experiments. Multiple configs can be provided and also individual arguments. Parameters are overridden left to right as they are given in the command line, which is the standard behavior of CLIs. The docs explain the [override-order](https://jsonargparse.readthedocs.io/en/v4.26.2/#override-order).

For example:
```shell
cli.py --config common.yaml --config overrides.yaml --individual.argument value
```

And it is possible to reference configs within another config. Thus, you can have a `config.yaml` as:
```yaml
model: modelX.yaml
data: dataY.yaml
```
where `modelX.yaml` and `dataY.yaml` contain the settings for each of the groups. However, there isn't really a need to have an additional config for this case. Instead of providing a single config with the previous content, the same can be run as:
```shell
cli.py --model modelX.yaml --data dataY.yaml
```

Also there is already a related issue, see #221.
