### ISSUE TITLE
unexpected behavior difference between parse_args and parse_known_args?

### ISSUE THREAD

**Issue by iclementine** [omni-us/jsonargparse#6]
I appreciate the flexibility jsonargparse offers us. But I think I've found some unexpected behaviors.

When adding an argument whos details you don't want to specify, and leaving it to be what ever is loaded from the yaml config file, for example, a dict, then if you parse with parse_args(), you would get the expected behavior. But if you pass an unkown argument , it would raise an Error, because unknown args are not allowed.

However, if you parse with parse_known_args, unkwon args are allowed, but you would not get the above behavior. 

```
import jsonargparse

parser = jsonargparse.ArgumentParser()
parser.add_argument("--run", help="run configs") # leave it to be specified by the config file
parser.add_argument("--config", action=jsonargparse.ActionConfigFile, help="config file")

args = parser.parse_args() # change it to args, _ = parser.parse_known_args()
print(args)
```

```yaml
run:
  speed: 30
  loop: 40
```

```
# parse_args
# namespace(__cwd__=['/workspace/projects/Parakeet/playground'], config=[Path(path="example.yaml", abs_path="/workspace/projects/Parakeet/playground/example.yaml", cwd="/workspace/projects/Parakeet/playground")], 
run=namespace(loop=40, speed=30))

# parse_known_args
# Namespace(__cwd__=['/workspace/projects/Parakeet/playground'], config=[Path(path="example.yaml", abs_path="/workspace/projects/Parakeet/playground/example.yaml", cwd="/workspace/projects/Parakeet/playground")], 
run=None, **{'run.loop': 40, 'run.speed': 30})
```

**Comment by nischalhp** [comment]
Adding as reference : https://docs.python.org/3.4/library/argparse.html#partial-parsing

**Comment by mauvilsa** [comment]
@iclementine thank you very much for reporting this issue. It illustrates two cases on how
jsonargparse is not intended to be used, and I had not considered these yet. So
great feedback to know how to improve things a bit.

Among the main motivations when the development of jsonargparse started, was to
make consistent parsing from command line arguments, configuration files and
environment variables, and also to note as early as possible bugs in code or in
configs.

Your first case, not specifying a type for an argument is not the intended way
to define an argument that can contain a dictionary with any content. It is
better to be explicit on what each argument is, and also it wouldn't be possible
to specify the same value (dict) through a command line argument or through an
environment variable. At the end you can see how this should be done.

Your second case, using parse_known_args has the problem that if someone makes a
mistake/typo in an argument or a config file, this would go unnoticed. So this
goes against noting as early as possible bugs. It was never intended to support
parse_known_args. But since jsonargparse is just an extension of argparse, then
the original parse_known_args was being called, and thus giving that weird
result.

I have changed the code so that both cases fail now. The first gives an error
suggesting to use the ActionJsonSchema as explained below. The second gives a
not implemented error, saying the reason why. If you or other anyone else think
that parse_known_args is required for some case I might consider implementing
it. But I will ask exactly what the use case is and probably will just respond
with an safer alternative that does not require a behavior like
parse_known_args.

Now, regarding how to do what you I think you intended. Suppose you have a config
file issue6.yaml with the same contents as you initially proposed:

    run:
      speed: 30
      loop: 40

Then you would define the parser and run the parser as follows. Note the
consistency in parsing arguments, config and environment variable.

    from jsonargparse import ArgumentParser, ActionConfigFile, ActionJsonSchema

    parser = ArgumentParser(env_prefix='APP')
    parser.add_argument("--run", action=ActionJsonSchema(schema={'type': 'object'}))
    parser.add_argument("--config", action=ActionConfigFile)

    args0 = parser.parse_args(['--run', '{"speed": 30, "loop": 40}'])
    args1 = parser.parse_args(['--config', 'issue6.yaml'])
    args2 = parser.parse_args(['--config', '{"run":{"speed": 30, "loop": 40}}'])
    args3 = parser.parse_path('issue6.yaml')
    args4 = parser.parse_env(env={'APP_RUN': '{"speed": 30, "loop": 40}'})

    print('# args0:  ', args0.run)
    print('# args1:  ', args1.run)
    print('# args2:  ', args2.run)
    print('# args3:  ', args3.run)
    print('# args4:  ', args4.run)

Running this script would result in the same value for all parsing runs

    # args0:  namespace(loop=40, speed=30)
    # args1:  namespace(loop=40, speed=30)
    # args2:  namespace(loop=40, speed=30)
    # args3:  namespace(loop=40, speed=30)
    # args4:  namespace(loop=40, speed=30)

Naturally it would be better if a more specific json schema is given for the run
argument, instead of the generic one used that accepts anything.

**Comment by iclementine** [comment]
Thank you.
I think adding

```python
action=ActionJsonSchema(schema={'type': 'object'})
```
is a good idea.

Here is why I want some *unsfae* behaviors with jsonargparse. When we use argparse we want to specify every argument, its name, type, default and help msg. The `ArgumentParser` works like a schema. This is safe and cool, because we would not need to cast the value.

While configparse and other libraries designed for parsing config files do not care about schema, they just leave it whatever loaded from the file. For naive config files like `ini`, we need to cast for type manually. (But for yaml or json, we can specify type in the config file, so it is more convenient to use configparse-like libraries to parse config files. They are not as safe as argparse, no schema, no help msg, no default value, but it is convenient.)

So I would appreciate the flexibility between strict argsparse and loose configparse. In most of the cases, we can specify every key in the parser, but when we want some unsafe behavior, we can use a generic schema.

For example, in a deep learning project, we may want to use different optimizers. But different optimizer subclasses may have different keys to specify. So may be a generic `--optimizer` is more flexible. Probably there is better solution for this.

```python
optimizer:
  type: 'momentum'
  lr: 0.01
  momentum: 0.9
```

```python
optimizer:
  type: 'adam'
  lr: 0.01
  beta1: 0.9
  beta2: 0.999
```

**Comment by mauvilsa** [comment]
I agree that using ActionJsonSchema with that generic schema can be the appropriate choice, since writing a schema for all possible optimizers would be a pain. But maybe this would be the appropriate choice only for research and development. If the code would be more for production and be expected that end users change the configuration, it might be worth writing a schema for the optimizer.

**Comment by iclementine** [comment]
Yes, I agree. When the code is for production, solely depending on config files without a schema is unsafe and confusing. It is a choice for only research and fast development.
