### ISSUE TITLE
datetime.timedelta signature is not working

### ISSUE THREAD

**Issue by gurvindersingh** [omni-us/jsonargparse#62]
It seems `datetime.timedelta` use `__new__` instead of `__init__` for instance creation. [Refer](https://github.com/python/cpython/blob/main/Lib/datetime.py#L461-L462) This is causing trouble when trying to use timedelta types in the config files.

**Comment by gurvindersingh** [comment]
Pinging @mauvilsa for reference from `pytorch-lightning` slack

**Comment by mauvilsa** [comment]
The classes that used `__new__` were not supported and with the latest commit to master this has been added. Unfortunately `datetime.timedelta` still does not work. It seems there is a deeper issue with the classes in `datetime` which prevent getting its signature. I have commented in a python bug ticket to see what people say about this, see [issue40897](https://bugs.python.org/issue40897?@ok_message=msg%20397248%20created%0Aissue%2040897%20nosy_count%2C%20nosy%2C%20messages%2C%20message_count%20edited%20ok&@template=item#msg397248).

**Comment by mauvilsa** [comment]
The problem seems to be cpython built-in classes which makes me doubt that it will be fixed any time soon or be ever fixed for older python versions.

As an alternative, from jsonargparse v3.17.0 the `datetime.timedelta` class will be registered as a type. This means that in config files it has to be represented as a string like `h:m:s` or `d days, h:m:s`.
