### ISSUE TITLE
Optional class instances

### ISSUE THREAD

**Issue by hadipash** [omni-us/jsonargparse#624]
Hello! I would like to ask what is a good way to handle optional class instances? For example, instantiating a validation dataset. In the original Python code, it would look like this:
```python
if args.val_dataset is not None:
    # instantiate the validation set class
```
However, `add_class_arguments()` doesn't support optional instances. To work around this, I'm currently using `add_subclass_arguments(required=False)`, but I find this approach suboptimal. Is there a better way to handle situations like this in `jsonargparse`? Thank you.

**Comment by hadipash** [comment]
Because the class I would like to instantiate is known and is not a subclass. Moreover, running `python train.py --help` will output this
```
--valid.dataset.help CLASS_PATH_OR_NAME
                        Show the help for the given subclass of ImageVideoDataset and exit.
--valid.dataset CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE
                        One or more arguments specifying "class_path" and "init_args" for any subclass of ImageVideoDataset. (type: Optional[ImageVideoDataset], default: null, known
                        subclasses: moviegen.dataset.ImageVideoDataset)
```
instead of the list of arguments. I can use `python train.py --valid.dataset.help ImageVideoDataset` to see them, but it's less intuitive in my opinion. Thanks!

**Comment by mauvilsa** [comment]
> It will be nice if add_class_arguments() and add_function_arguments() supported required parameter as well. Thank you!

The way these work is that they add a group of arguments corresponding to the parameters of the function/class. But all added arguments are independent so they will always be part of the parsed namespace. It is not possible to have an optional group in argparse.

> Because the class I would like to instantiate is known in advance and is not a subclass.

Since v4.29.0 it is possible to provide to a subclass without providing `class_path`. In such a case the base class is used. So at least in a config file the content and individual command line arguments can be the same as for `add_class_arguments`. Though, `--print_config`/`dump`/`save` would have `class_path` and `init_args`.

> Moreover, running python train.py --help will output this

Somewhat related I have been working on https://github.com/omni-us/jsonargparse/issues/287#issuecomment-2433109024. My idea is that in the future there wouldn't be a difference between subclasses and dataclasses. A part of this that I was planning is to make the class path for help optional, and if not given, then the help for the base class is printed, i.e. it would look like
```
--valid.dataset.help [CLASS_PATH_OR_NAME]
```
and running `cli.py --valid.dataset.help` would give the help.

I do agree that it is not ideal even with these possible improvements. But note that inevitably these automatic creation of parsers from signatures will have some limitations and compromises.

**Comment by hadipash** [comment]
Thank you for your detailed reply. `jsonargparse` significantly simplifies parsers creation and reduces boilerplate code. So, its minor limitations are not a big trade-off. 👍
