### ISSUE TITLE
Cant pass arguments with callable types

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#655]
## 🐛 Bug report

This is a follow-up to https://github.com/omni-us/jsonargparse/issues/653#issuecomment-2562464168. That solution did work for the Optimizer, but not for a trivial model class.

```shell
usage: kk2.py [-h] [--my_config CONFIG] [--my_config.f CONFIG] --my_config.f.f F [--my_config.model.help [CLASS_PATH_OR_NAME]] --my_config.model MODEL
error: Parser key "my_config.model":
  Type typing.Callable[[typing.Any, ...], __main__.Model] expects a function or a callable class: Validation failed: Key 'a' is not expected. Got value: Namespace(class_path='__main__.Model', init_args=Namespace(a='-123'))
```

### To reproduce

```python
from dataclasses import dataclass
from jsonargparse import ArgumentParser
from typing import Callable, Any

@dataclass
class Foo:
    f: int

class Model:
    def __init__(self, a: int):
        self.a = a

@dataclass
class MyConfig:
    f: Foo
    model: Callable[[Any], Model]

parser = ArgumentParser()
parser.add_class_arguments(MyConfig, nested_key="my_config")
args = parser.parse_args(args=["--my_config.f.f=123", "--my_config.model=__main__.Model", "--my_config.model.a=-123"])
print(args.my_config)
init = parser.instantiate_classes(args)
print(init.my_config)
```

The printed config also does not include the `a` argument so it seems like jsonargparse fails to parse it entirely.

This repro snippet can be slimmed down further, but I wanted to keep the the broad strokes of my actual script

This does work somehow:

```python
from dataclasses import dataclass
from jsonargparse import ArgumentParser
import torch
from typing import Callable, Any

@dataclass
class Foo:
    f: int

@dataclass
class MyConfig:
    f: Foo
    model: Callable[[Any], torch.optim.Optimizer]

parser = ArgumentParser()
parser.add_class_arguments(MyConfig, nested_key="my_config")
args = parser.parse_args(args=["--my_config.f.f=123", "--my_config.model=torch.optim.AdamW", "--my_config.model.lr=-123"])
print(args.my_config)
init = parser.instantiate_classes(args)
print(init.my_config)
```

**Comment by mauvilsa** [comment]
Actually this is working as expected. Note the type `Callable[[Any], torch.optim.Optimizer]`. In `model` expects a function that receives a single positional (`params`) when called. This implies that `params` can't come from the parser, i.e. it is not configurable, because it should be given when calling the function. That is why `--print_config` wouldn't include `params` and a config including `params` would produce a parsing error.

If you wanted to do the same for `Model`, the case is different because you would like all parameters to be configurable. In the code above `a` would be non-configurable because of `[Any]`. The correct type would be `Callable[[], Model]`, i.e. a function that receives zero parameters and returns an instance of `Model`.

**Comment by carmocca** [comment]
Okay! That makes sense. I thought the arguments in the callable annotation were the arguments for the output type. But no, it's only the arguments of the output type that are not provided by the CLI. Makes sense now.

Thank you again
