### ISSUE TITLE
Optional with float won't parse.

### ISSUE THREAD

**Issue by stasbel** [omni-us/jsonargparse#67]
```python3
import jsonargparse
from typing import Optional

parser = jsonargparse.ArgumentParser()
parser.add_argument('--arg', type=Optional[float], default=1e-6)
parser.parse_args(['--arg=1e-5'])
```
=>
```
Parser key "arg": Value "1e-5" does not validate against any of the types in typing.Union[float, NoneType]:
  - Expected a <class 'float'> but got "1e-5"
  - Expected a <class 'NoneType'> but got "1e-5"
```

**Comment by mauvilsa** [comment]
This is not related to jsonargparse. The issue is that pyyaml implements YAML 1.1. According to that specification (see https://yaml.org/type/float.html) the value 1e-5 is not a valid float in scientific notation. Just change it to 1.0e-5.

**Comment by stasbel** [comment]
but,
```python3
import jsonargparse
from typing import Optional

parser = jsonargparse.ArgumentParser()
parser.add_argument('--arg', type=float, default=1e-6)
parser.parse_args(['--arg=1e-5'])
```
works just fine

**Comment by stasbel** [comment]
I do not use YAML anywhere in original example

**Comment by mauvilsa** [comment]
It issue is not about you thinking that you have not used yaml. The type hint support is all based on using pyyaml. For example if you have a type as `Optional[Union[float, List[float], Dict[int, float]]]`, the given value can be any of those types. Whenever a type hint is given it is pyyaml who parses the value. The normal `type=float` does work because it does not use the type hint support. It just casts to float which does allow that scientific notation.

**Comment by stasbel** [comment]
okay, that explains it, thanks
from internal implementation perspective, it does make sense
but still, from a user perspective, I don't expect my scripts to stop working when I just add Optional typing to it
I close it for now, feel free to reopen if there is something left to discuss :)

**Comment by mauvilsa** [comment]
Since jsonargparse version 4.1.0 a float such as `1e-5` will parse correctly with both `float` and `Optional[float]` types.
