### ISSUE TITLE
Error when parsing config file with `type=Path`

### ISSUE THREAD

**Issue by alealv** [omni-us/jsonargparse#94]
## How to reproduce
```python
from jsonargparse import ArgumentParser
from pathlib import Path

parser = ArgumentParser()
parser.add_argument("--path", type=Path)
parser.parse_args(["--path", "any/path"])
```
## Error
`test.py: error: Parser key "output_dir": not enough values to unpack (expected 2, got 1)`

## Version

```bash
➜ pip list | grep jsonarg
jsonargparse                       3.19.3
```

## Tracing
The error fails [here](https://github.com/omni-us/jsonargparse/blob/2f47c4dd2fc79796cc26c56dffe9e60da07efe0d/jsonargparse/util.py#L295) and it's called from [here](https://github.com/omni-us/jsonargparse/blob/master/jsonargparse/typehints.py#L451).

**Comment by mauvilsa** [comment]
Thank you for reporting!

Note that `pathlib.Path` is not supported as a core type. What is happening when you add an argument with `type=Path` is that it creates a subclass argument, see https://jsonargparse.readthedocs.io/en/stable/#class-type-and-sub-classes. The `not enough values to unpack` error is a bug since it should be giving the same error as if you did `parser.parse_args(["--path", "any/path.ext"])`. Will look at this.

Also note that jsonargparse has specific types for checking paths, see https://jsonargparse.readthedocs.io/en/stable/#parsing-paths. If you specifically want  `pathlib.Path` as a core type, then you can register it, see https://jsonargparse.readthedocs.io/en/stable/#registering-types.

**Comment by mauvilsa** [comment]
Even though `pathlib.Path` can be registered, it is not very useful. The issue is that `pathlib.Path` accepts any string, thus no validation and the point of the parser is that values are validated and fail if invalid. That is why there are path types in jsonargparse which do validation.

**Comment by alealv** [comment]
Thanks for the explanation.

I noticed that `jsonargparse` has specific Path type checking but I just wanted to have an object of type `pathlib.Path` and do the validation or dir creation afterward in the code.
